FROM nvidia/cuda:12.6.1-devel-ubuntu22.04

# Set the working directory
WORKDIR /pai

# Install dependencies in a single layer to optimize caching
RUN apt update && apt upgrade -y && \
    apt-get install -y \
        net-tools \
        software-properties-common \
        python3.10 \
        python-is-python3 \
        python3-pip \
        python3.10-distutils \
        npm \
        libsndfile1 \
        libasound2-dev \
        ffmpeg \
        autotools-dev \
        automake \
        libtool \
        curl \
        git && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    curl https://bootstrap.pypa.io/get-pip.py | python && \
    apt-get clean

# Clone and build eSpeak-NG separately
RUN git clone https://github.com/espeak-ng/espeak-ng.git /pai/espeak-ng
WORKDIR /pai/espeak-ng
RUN ./autogen.sh && ./configure --without-pulseaudio && make && make install

# Copy only package files first to leverage Docker's cache for dependencies
WORKDIR /pai/web
COPY web/package.json web/package-lock.json ./
RUN npm install

WORKDIR /pai/api
COPY api/requirements.txt ./
RUN pip3 install -r requirements.txt

RUN CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python --upgrade --force-reinstall --no-cache-dir
RUN pip install --ignore-installed --no-cache-dir -U blinker
RUN pip3 install TTS
RUN pip3 install simpleaudio gtts fastapi==0.112.0

ENV OPENAI_API_KEY=${OPENAI_API_KEY:-"DUMMY-KEY"}

# Now copy the rest of the project files
COPY . /pai

# Expose port 4000 for the application
EXPOSE 4000

CMD ["npm", "start", "--prefix", "/pai/web"]
