FROM nvidia/cuda:12.4.0-devel-ubuntu22.04

# Set the working directory inside the container
WORKDIR /pai


RUN apt update && apt upgrade -y
RUN apt-get update
RUN apt install net-tools -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update
RUN apt install python3.10 -y
RUN apt install python-is-python3 -y
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
RUN update-alternatives --config python3
# RUN curl https://bootstrap.pypa.io/get-pip.py | python
RUN apt install python3-pip -y
RUN apt install python3.10-distutils -y
RUN apt install npm -y
RUN apt-get install libsndfile1 -y
RUN apt install libasound2-dev -y
RUN apt install ffmpeg -y
RUN apt-get install autotools-dev -y
RUN apt-get install automake -y
RUN apt-get install libtool -y
RUN git clone https://github.com/espeak-ng/espeak-ng.git
WORKDIR /pai/espeak-ng
RUN ./autogen.sh
RUN ./configure --without-pulseaudio
RUN make
RUN make install

# Copy the current directory contents into the container at /pai
COPY . /pai

WORKDIR /pai/web
RUN npm install
WORKDIR /pai/api
RUN pip3 install --no-cache-dir --no-deps -r requirements.txt
RUN CMAKE_ARGS="-DGGML_CUDA=on" pip3 install llama-cpp-python --upgrade --force-reinstall --no-cache-dir
# RUN pip3 install TTS simpleaudio gtts
RUN git clone --branch v0.22.0 --single-branch https://github.com/coqui-ai/TTS /TTS \
    && cd /TTS \
    && sed -i 's/gruut\[de,es,fr\]==2.2.3/gruut\[de,es,fr\]==2.4.0/' requirements.txt \
    && pip install -r requirements.txt \
    && pip3 install .
RUN pip3 install simpleaudio gtts
WORKDIR /pai

# Expose port 4000 for the application
EXPOSE 4000

# Correctly use the --prefix option by separating it and its argument
# CMD ["npm", "start", "--prefix", "/pai/web"]
ENTRYPOINT ./start.sh
